# This is a basic workflow to help you get started with Actions

name: Get Latest Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron:  '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.G_TOKEN }}
      - name: Fetch all releases
        run: |
            repos=$(jq -r '.repos' "repos.json")
            for i in $(echo "${repos}" | jq -r '.[] | @base64'); 
            do              
              curl -sL "https://api.github.com/repos/$(jq, '.owner')/$(_jq, '.name')/releases" | \
              touch "release-versions/$(jq, '.name')-latest.txt" | \
              jq > "release-versions/$(jq, '.name')-latest.txt"
            done
          
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release versions
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --local user.name "Latest Version Helper"
          git add release-versions/
          git commit -m "New Releases"
          git push
