# This is a basic workflow to help you get started with Actions

name: Get Latest Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron:  '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.G_TOKEN }}
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/bozbez/win-capture-audio/releases | \
          jq > release-versions/win-capture-audio-latest.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --local user.name ${{ github.actor }}
          git add release-versions/win-capture-audio.latest.txt
          git commit -m "New release version"
          git push
